version: '3'

tasks:
  default:
    desc: List all tasks
    cmds:
      - task --list-all
  
  cache:
    desc: Cache dependencies
    cmds:
      - go fmt ./...
      - go mod tidy

  stop:
    desc: Stop service
    cmds:
      - docker-compose down --volumes

  start:
    desc: Start service
    deps:
      - stop
      - cache
    cmds:
      - docker-compose up --build --force-recreate

  test:
    desc: Testing packages
    cmds:
      - go test -v -count 1 {{.CLI_ARGS}}

  env:
    desc: Secret management with Infisical
    cmds:
      - infisical secrets --path=/coffeesaurus {{.CLI_ARGS}}